<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Database\Seeder;

class StoreDemoSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $categories = collect([
            [
                'name' => 'Women Cloths',
                'slug' => 'women-cloths',
                'description' => 'Curated silhouettes for premium everyday dressing.',
                'accent' => '#3457ff',
            ],
            [
                'name' => 'Man Cloths',
                'slug' => 'man-cloths',
                'description' => 'Tailored essentials and soft knit staples.',
                'accent' => '#0f766e',
            ],
            [
                'name' => 'Kid Cloths',
                'slug' => 'kid-cloths',
                'description' => 'Playful fits built for comfort and motion.',
                'accent' => '#d97706',
            ],
            [
                'name' => 'Sweater',
                'slug' => 'sweater',
                'description' => 'Layering pieces with texture and seasonal weight.',
                'accent' => '#7c3aed',
            ],
        ])->mapWithKeys(function (array $category): array {
            $model = Category::query()->updateOrCreate(
                ['slug' => $category['slug']],
                $category,
            );

            return [$category['slug'] => $model];
        });

        collect([
            [
                'category_slug' => 'women-cloths',
                'name' => 'T-Shirt',
                'slug' => 't-shirt',
                'sku' => 'SPD-TS-001',
                'tagline' => 'Soft cotton tee with structured shoulders.',
                'description' => 'A polished staple for daily merchandising layouts.',
                'price' => 79.80,
                'compare_at_price' => 98.00,
                'inventory' => 79,
                'status' => 'scheduled',
                'is_featured' => true,
                'theme' => 'cobalt',
                'rating' => 4.90,
                'reviews_count' => 124,
            ],
            [
                'category_slug' => 'man-cloths',
                'name' => 'Shirt',
                'slug' => 'shirt',
                'sku' => 'SPD-SH-002',
                'tagline' => 'Lightweight overshirt for smart layering.',
                'description' => 'Built to shift between formal edits and casual sets.',
                'price' => 76.89,
                'compare_at_price' => 84.00,
                'inventory' => 86,
                'status' => 'active',
                'is_featured' => true,
                'theme' => 'forest',
                'rating' => 4.76,
                'reviews_count' => 93,
            ],
            [
                'category_slug' => 'kid-cloths',
                'name' => 'Pant',
                'slug' => 'pant',
                'sku' => 'SPD-PT-003',
                'tagline' => 'Relaxed cotton pant for all-day comfort.',
                'description' => 'Easy waisted fit with durable finishing.',
                'price' => 86.65,
                'compare_at_price' => null,
                'inventory' => 74,
                'status' => 'draft',
                'is_featured' => false,
                'theme' => 'sand',
                'rating' => 4.63,
                'reviews_count' => 58,
            ],
            [
                'category_slug' => 'man-cloths',
                'name' => 'Sweater Core',
                'slug' => 'sweater-core',
                'sku' => 'SPD-SW-004',
                'tagline' => 'Compact knit with a clean hem finish.',
                'description' => 'An easy merchandising anchor for cooler drops.',
                'price' => 56.07,
                'compare_at_price' => 68.00,
                'inventory' => 69,
                'status' => 'active',
                'is_featured' => false,
                'theme' => 'graphite',
                'rating' => 4.72,
                'reviews_count' => 81,
            ],
            [
                'category_slug' => 'man-cloths',
                'name' => 'Sweater Studio',
                'slug' => 'sweater-studio',
                'sku' => 'SPD-SW-005',
                'tagline' => 'Textured sweater developed for editorial drops.',
                'description' => 'A premium seasonal line item with soft hand feel.',
                'price' => 56.07,
                'compare_at_price' => null,
                'inventory' => 69,
                'status' => 'scheduled',
                'is_featured' => true,
                'theme' => 'midnight',
                'rating' => 4.87,
                'reviews_count' => 104,
            ],
            [
                'category_slug' => 'women-cloths',
                'name' => 'Light Jacket',
                'slug' => 'light-jacket',
                'sku' => 'SPD-LJ-006',
                'tagline' => 'Crisp outer layer for transitional weather.',
                'description' => 'Refined volume with minimal detailing.',
                'price' => 36.00,
                'compare_at_price' => 44.00,
                'inventory' => 65,
                'status' => 'draft',
                'is_featured' => false,
                'theme' => 'sky',
                'rating' => 4.51,
                'reviews_count' => 45,
            ],
            [
                'category_slug' => 'man-cloths',
                'name' => 'Half Shirt',
                'slug' => 'half-shirt',
                'sku' => 'SPD-HS-007',
                'tagline' => 'Short sleeve shirt with elevated drape.',
                'description' => 'Strong conversion performer for summer capsules.',
                'price' => 46.78,
                'compare_at_price' => 58.00,
                'inventory' => 58,
                'status' => 'active',
                'is_featured' => true,
                'theme' => 'ink',
                'rating' => 4.78,
                'reviews_count' => 89,
            ],
            [
                'category_slug' => 'sweater',
                'name' => 'Half Shirt Knit',
                'slug' => 'half-shirt-knit',
                'sku' => 'SPD-HS-008',
                'tagline' => 'Boxy cropped knit with tonal ribbing.',
                'description' => 'High-contrast styling piece for campaign edits.',
                'price' => 46.78,
                'compare_at_price' => null,
                'inventory' => 58,
                'status' => 'active',
                'is_featured' => false,
                'theme' => 'plum',
                'rating' => 4.66,
                'reviews_count' => 67,
            ],
            [
                'category_slug' => 'man-cloths',
                'name' => 'Half Shirt Jacket',
                'slug' => 'half-shirt-jacket',
                'sku' => 'SPD-HS-009',
                'tagline' => 'Weighted shirt-jacket in deep indigo.',
                'description' => 'Carries editorial visual depth without extra bulk.',
                'price' => 46.78,
                'compare_at_price' => 60.00,
                'inventory' => 58,
                'status' => 'scheduled',
                'is_featured' => true,
                'theme' => 'denim',
                'rating' => 4.83,
                'reviews_count' => 73,
            ],
            [
                'category_slug' => 'kid-cloths',
                'name' => 'Half Shirt Kids',
                'slug' => 'half-shirt-kids',
                'sku' => 'SPD-HS-010',
                'tagline' => 'Easy-fit kids shirt in a clean poplin finish.',
                'description' => 'Bright visual tone for family catalog stories.',
                'price' => 46.78,
                'compare_at_price' => null,
                'inventory' => 58,
                'status' => 'active',
                'is_featured' => false,
                'theme' => 'lilac',
                'rating' => 4.58,
                'reviews_count' => 38,
            ],
        ])->each(function (array $product) use ($categories): void {
            Product::query()->updateOrCreate(
                ['sku' => $product['sku']],
                [
                    'category_id' => $categories[$product['category_slug']]->id,
                    'name' => $product['name'],
                    'slug' => $product['slug'],
                    'tagline' => $product['tagline'],
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'compare_at_price' => $product['compare_at_price'],
                    'inventory' => $product['inventory'],
                    'status' => $product['status'],
                    'is_featured' => $product['is_featured'],
                    'theme' => $product['theme'],
                    'rating' => $product['rating'],
                    'reviews_count' => $product['reviews_count'],
                ],
            );
        });

        collect([
            [
                'number' => 'NS-1001',
                'status' => 'delivered',
                'customer_name' => 'Jamie Carter',
                'email' => 'jamie@example.com',
                'phone' => '+1-202-555-0101',
                'address_line1' => '15 Mercer Street',
                'address_line2' => null,
                'city' => 'New York',
                'postal_code' => '10012',
                'notes' => 'Leave at front desk.',
                'subtotal_amount' => 159.60,
                'shipping_amount' => 12.00,
                'total_amount' => 171.60,
                'placed_at' => now()->subDays(8),
            ],
            [
                'number' => 'NS-1002',
                'status' => 'processing',
                'customer_name' => 'Morgan Lee',
                'email' => 'morgan@example.com',
                'phone' => '+1-202-555-0122',
                'address_line1' => '245 Sunset Avenue',
                'address_line2' => 'Suite 8',
                'city' => 'Los Angeles',
                'postal_code' => '90028',
                'notes' => null,
                'subtotal_amount' => 122.85,
                'shipping_amount' => 10.00,
                'total_amount' => 132.85,
                'placed_at' => now()->subDays(5),
            ],
            [
                'number' => 'NS-1003',
                'status' => 'pending',
                'customer_name' => 'Avery Kim',
                'email' => 'avery@example.com',
                'phone' => '+1-202-555-0143',
                'address_line1' => '88 Harbor Road',
                'address_line2' => null,
                'city' => 'Seattle',
                'postal_code' => '98101',
                'notes' => 'Call on arrival.',
                'subtotal_amount' => 92.78,
                'shipping_amount' => 8.50,
                'total_amount' => 101.28,
                'placed_at' => now()->subDays(2),
            ],
            [
                'number' => 'NS-1004',
                'status' => 'shipped',
                'customer_name' => 'Riley Brooks',
                'email' => 'riley@example.com',
                'phone' => '+1-202-555-0174',
                'address_line1' => '402 Lake Drive',
                'address_line2' => null,
                'city' => 'Chicago',
                'postal_code' => '60611',
                'notes' => null,
                'subtotal_amount' => 181.20,
                'shipping_amount' => 14.00,
                'total_amount' => 195.20,
                'placed_at' => now()->subDay(),
            ],
        ])->each(function (array $order): void {
            Order::query()->updateOrCreate(
                ['number' => $order['number']],
                $order,
            );
        });
    }
}
